version: '3.7'

services:
  office:
    build: .
    container_name: 'office'
    volumes:
      - .:/app
    ports:
      - "32800:8000"
    depends_on:
      - office_database

  office_database:
    image: mysql:5.7
    container_name: 'office_database'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: office_database
