# Generated by Django 2.2.6 on 2019-11-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('cpf', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CPF')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Nome')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Celular')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Anunciantes')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('destiny', models.CharField(max_length=50, verbose_name='Destinatário')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('personalContact', models.ManyToManyField(to='app.UserDetails', verbose_name='Contato associado')),
            ],
            options={
                'db_table': 'demands',
            },
        ),
    ]
